// Keymap reference : https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf#%5B%7B%22num%22%3A936%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C120%2C717%2Cnull%5D

const MOD_LEFT_CTRL = 1 << 8;
const MOD_LEFT_SHIFT = 1 << 9;
const MOD_LEFT_ALT = 1 << 10;
const MOD_LEFT_GUI = 1 << 11;
const MOD_RIGHT_CTRL = 1 << 12;
const MOD_RIGHT_SHIFT = 1 << 13;
const MOD_RIGHT_ALT = 1 << 14;
const MOD_RIGHT_GUI = 1 << 15;

const CODE_LAYER_PRESS = 255;
const CODE_LAYER_RELEASE = 254;

// The default is a US layout
function getKeyLayout(local_keylayout) {
  const keylayout = {
    0x04: ["Keya", "a"],
    0x05: ["Keyb", "b"],
    0x06: ["Keyc", "c"],
    0x07: ["Keyd", "d"],
    0x08: ["Keye", "e"],
    0x09: ["Keyf", "f"],
    0x0a: ["Keyg", "g"],
    0x0b: ["Keyh", "h"],
    0x0c: ["Keyi", "i"],
    0x0d: ["Keyj", "j"],
    0x0e: ["Keyk", "k"],
    0x0f: ["Keyl", "l"],
    0x10: ["Keym", "m"],
    0x11: ["Keyn", "n"],
    0x12: ["Keyo", "o"],
    0x13: ["Keyp", "p"],
    0x14: ["Keyq", "q"],
    0x15: ["Keyr", "r"],
    0x16: ["Keys", "s"],
    0x17: ["Keyt", "t"],
    0x18: ["Keyu", "u"],
    0x19: ["Keyv", "v"],
    0x1a: ["Keyw", "w"],
    0x1b: ["Keyx", "x"],
    0x1c: ["Keyy", "y"],
    0x1d: ["Keyz", "z"],
    0x1e: ["Digit1", "1"],
    0x1f: ["Digit2", "2"],
    0x20: ["Digit3", "3"],
    0x21: ["Digit4", "4"],
    0x22: ["Digit5", "5"],
    0x23: ["Digit6", "6"],
    0x24: ["Digit7", "7"],
    0x25: ["Digit8", "8"],
    0x26: ["Digit9", "9"],
    0x27: ["Digit0", "0"],
    0x28: ["Enter"],
    0x29: ["Escape"],
    0x2a: ["Backspace"],
    0x2b: ["Tab"],
    0x2c: ["Space", " "],
    0x2d: ["Minus", "-"],
    0x2e: ["Equal", "="],
    0x2f: ["BracketLeft", "["],
    0x30: ["BracketRight", "]"],
    0x31: ["BackSlash", "\\"],
    // 0x32
    0x33: ["Semicolon", ";"],
    0x34: ["Quote", "'"],
    0x35: ["Backquote", "`"],
    0x36: ["Comma", ","],
    0x37: ["Period", "."],
    0x38: ["Slash", "/"],
    0x39: ["CapsLock"],
    0x3a: ["F1"],
    0x3b: ["F2"],
    0x3c: ["F3"],
    0x3d: ["F4"],
    0x3e: ["F5"],
    0x3f: ["F6"],
    0x40: ["F7"],
    0x41: ["F8"],
    0x42: ["F9"],
    0x43: ["F10"],
    0x44: ["F11"],
    0x45: ["F12"],
    0x46: ["PrintScreen"],
    0x47: ["ScrollLock"],
    0x48: ["Pause"],
    0x49: ["Insert"],
    0x4a: ["Home"],
    0x4b: ["PageUp"],
    0x4c: ["Delete"],
    0x4d: ["End"],
    0x4e: ["PageDown"],
    0x4f: ["ArrowRight"],
    0x50: ["ArrowLeft"],
    0x51: ["ArrowDown"],
    0x52: ["ArrowUp"],
    0x53: ["KeypadNumLock"],
    0x54: ["KeypadDivide"],
    0x55: ["KeypadMultiply"],
    0x56: ["KeypadSubtract"],
    0x57: ["KeypadAdd"],
    0x58: ["KeypadEnter"],
    0x59: ["Keypad1"],
    0x5a: ["Keypad2"],
    0x5b: ["Keypad3"],
    0x5c: ["Keypad4"],
    0x5d: ["Keypad5"],
    0x5e: ["Keypad6"],
    0x5f: ["Keypad7"],
    0x60: ["Keypad8"],
    0x61: ["Keypad9"],
    0x62: ["Keypad0"],
    0x63: ["KeypadPeriod"],
    // 0x64

    [0x04 | MOD_LEFT_SHIFT]: ["KeyA", "A"],
    [0x05 | MOD_LEFT_SHIFT]: ["KeyB", "B"],
    [0x06 | MOD_LEFT_SHIFT]: ["KeyC", "C"],
    [0x07 | MOD_LEFT_SHIFT]: ["KeyD", "D"],
    [0x08 | MOD_LEFT_SHIFT]: ["KeyE", "E"],
    [0x09 | MOD_LEFT_SHIFT]: ["KeyF", "F"],
    [0x0a | MOD_LEFT_SHIFT]: ["KeyG", "G"],
    [0x0b | MOD_LEFT_SHIFT]: ["KeyH", "H"],
    [0x0c | MOD_LEFT_SHIFT]: ["KeyI", "I"],
    [0x0d | MOD_LEFT_SHIFT]: ["KeyJ", "J"],
    [0x0e | MOD_LEFT_SHIFT]: ["KeyK", "K"],
    [0x0f | MOD_LEFT_SHIFT]: ["KeyL", "L"],
    [0x10 | MOD_LEFT_SHIFT]: ["KeyM", "M"],
    [0x11 | MOD_LEFT_SHIFT]: ["KeyN", "N"],
    [0x12 | MOD_LEFT_SHIFT]: ["KeyO", "O"],
    [0x13 | MOD_LEFT_SHIFT]: ["KeyP", "P"],
    [0x14 | MOD_LEFT_SHIFT]: ["KeyQ", "Q"],
    [0x15 | MOD_LEFT_SHIFT]: ["KeyR", "R"],
    [0x16 | MOD_LEFT_SHIFT]: ["KeyS", "S"],
    [0x17 | MOD_LEFT_SHIFT]: ["KeyT", "T"],
    [0x18 | MOD_LEFT_SHIFT]: ["KeyU", "U"],
    [0x19 | MOD_LEFT_SHIFT]: ["KeyV", "V"],
    [0x1a | MOD_LEFT_SHIFT]: ["KeyW", "W"],
    [0x1b | MOD_LEFT_SHIFT]: ["KeyX", "X"],
    [0x1c | MOD_LEFT_SHIFT]: ["KeyY", "Y"],
    [0x1d | MOD_LEFT_SHIFT]: ["KeyZ", "Z"],
    [0x1e | MOD_LEFT_SHIFT]: ["ExclamationMark", "!"],
    [0x1f | MOD_LEFT_SHIFT]: ["At", "@"],
    [0x20 | MOD_LEFT_SHIFT]: ["Hashtag", "#"],
    [0x21 | MOD_LEFT_SHIFT]: ["Dollar", "$"],
    [0x22 | MOD_LEFT_SHIFT]: ["Percent", "%"],
    [0x23 | MOD_LEFT_SHIFT]: ["Caret", "^"],
    [0x24 | MOD_LEFT_SHIFT]: ["Ampersand", "&"],
    [0x25 | MOD_LEFT_SHIFT]: ["Star", "*"],
    [0x26 | MOD_LEFT_SHIFT]: ["ParenthesisLeft", "("],
    [0x27 | MOD_LEFT_SHIFT]: ["ParenthesisRight", ")"],
    // 0x28 - 0x2C
    [0x2d | MOD_LEFT_SHIFT]: ["Underscore", "_"],
    [0x2e | MOD_LEFT_SHIFT]: ["Plus", "+"],
    [0x2f | MOD_LEFT_SHIFT]: ["CurlyBracketLeft", "{"],
    [0x30 | MOD_LEFT_SHIFT]: ["CurlyBracketRight", "}"],
    [0x31 | MOD_LEFT_SHIFT]: ["Pipe", "|"],
    // 0x32
    [0x33 | MOD_LEFT_SHIFT]: ["Colon", ":"],
    [0x34 | MOD_LEFT_SHIFT]: ["DoubleQuote", '"'],
    [0x35 | MOD_LEFT_SHIFT]: ["Tilde", "~"],
    [0x36 | MOD_LEFT_SHIFT]: ["AngleBracketLeft", "<"],
    [0x37 | MOD_LEFT_SHIFT]: ["AngleBracketRight", ">"],
    [0x38 | MOD_LEFT_SHIFT]: ["QuestionMark", "?"],
    // 0x39 - 0x52
    [0x53 | MOD_LEFT_SHIFT]: ["KeypadClear"],
    [0x59 | MOD_LEFT_SHIFT]: ["KeypadEnd"],
    [0x5a | MOD_LEFT_SHIFT]: ["KeypadArrowDown"],
    [0x5b | MOD_LEFT_SHIFT]: ["KeypadPageDown"],
    [0x5c | MOD_LEFT_SHIFT]: ["KeypadArrowLeft"],
    [0x5e | MOD_LEFT_SHIFT]: ["KeypadArrowRight"],
    [0x5f | MOD_LEFT_SHIFT]: ["KeypadHome"],
    [0x60 | MOD_LEFT_SHIFT]: ["KeypadArrowUp"],
    [0x61 | MOD_LEFT_SHIFT]: ["KeypadPageUp"],
    [0x62 | MOD_LEFT_SHIFT]: ["KeypadInsert"],
    [0x63 | MOD_LEFT_SHIFT]: ["KeypadDelete"],
    // 0x64

    [MOD_LEFT_CTRL]: ["ControlLeft"],
    [MOD_LEFT_SHIFT]: ["ShiftLeft"],
    [MOD_LEFT_ALT]: ["AltLeft"],
    [MOD_LEFT_GUI]: ["MetaLeft"],
    [MOD_RIGHT_CTRL]: ["ControlRight"],
    [MOD_RIGHT_SHIFT]: ["ShiftRight"],
    [MOD_RIGHT_ALT]: ["AltRight"],
    [MOD_RIGHT_GUI]: ["MetaRight"],

    [(0 << 8) + CODE_LAYER_PRESS]: ["LayerPress1"],
    [(1 << 8) + CODE_LAYER_PRESS]: ["LayerPress2"],
    [(2 << 8) + CODE_LAYER_PRESS]: ["LayerPress3"],
    [(3 << 8) + CODE_LAYER_PRESS]: ["LayerPress4"],
    [(4 << 8) + CODE_LAYER_PRESS]: ["LayerPress5"],
    [(5 << 8) + CODE_LAYER_PRESS]: ["LayerPress6"],

    [(0 << 8) + CODE_LAYER_RELEASE]: ["LayerRelease1"],
    [(1 << 8) + CODE_LAYER_RELEASE]: ["LayerRelease2"],
    [(2 << 8) + CODE_LAYER_RELEASE]: ["LayerRelease3"],
    [(3 << 8) + CODE_LAYER_RELEASE]: ["LayerRelease4"],
    [(4 << 8) + CODE_LAYER_RELEASE]: ["LayerRelease5"],
    [(5 << 8) + CODE_LAYER_RELEASE]: ["LayerRelease6"],
  };

  if (local_keylayout) {
    for (const key in local_keylayout) {
      keylayout[key] = local_keylayout[key];
    }
  }

  return keylayout;
}
